version: "3.7"

# This compose file contains containers that should be pushed to docker hub as part of the core platform AND are run as part of the app at startup (configured to run in dev mode).

services:
  # hook in case we need to add init behavior
  # every root service (no depends_on) should depend on init
  init:
    container_name: init-dev
  seed:
    container_name: airbyte-data-seed-dev
  scheduler:
    container_name: airbyte-scheduler-dev
  server:
    container_name: airbyte-server-dev
  webapp:
    container_name: airbyte-webapp-dev
